### ISSUE TITLE
UG Guide Improvements

### ISSUE THREAD

**Issue by HanB1n** [AY2425S1-CS2103T-F15-4/tp#131]
Update the JAR File Link.
Remove all symbols of AB3
Update the screenshot of Help function

**Comment by HanB1n** [comment]
Edit headers to be more presentable and segregated
Make the examples relevant to our use case, remove the Prison stuff

**Comment by tingxuanp** [comment]
Update command summary

**Comment by HanB1n** [comment]
Fix hyperlinks

**Comment by tingxuanp** [comment]
Introduction: explicitly identify target users, assumptions, user-centric description of the product

**Comment by tingxuanp** [comment]
Make layout more suitable for skimming and scanning, more spacing etc 

could consider colour coding the features to make it easier to read?

**Comment by tingxuanp** [comment]
Update use cases examples for new commands
