### ISSUE TITLE
Find does not work in Wedding view

### ISSUE THREAD

**Issue by HanB1n** [AY2425S1-CS2103T-F15-4/tp#195]
![image](https://github.com/user-attachments/assets/d93a2595-dc08-4e4f-92a7-baeff06a83c6)

**Comment by tingxuanp** [comment]
Could I clarify what this means, do you mean the desired output is to search and list weddings or search and list contacts that are assigned to that wedding?

**Comment by HanB1n** [comment]
The current bug occurs when you switch to wedding view. When in wedding view, the find command would not execute as intended. Can refer to the screenshot, when i search for weddings containing 2 in the name, all the other weddings show up.
