### ISSUE TITLE
[PE-D][Tester B] Bug: find command does not give specific error message for `find w/`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-4/tp#270]
The following screenshot is produced by executing `find w/May`, which does not exist in the system.
The error message can be phrased more clearly such as saying "wedding not found" instead of "contacts not found".
![image.png](https://raw.githubusercontent.com/YANYAN-w/ped/main/files/d8e2b52a-7fca-4b40-a15e-dd9df17c9181.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: YANYAN-w/ped#1

**Comment by tingxuanp** [comment]
invalid bug. `find w/` searches for contacts assigned to the weddings and not the wedding itself. 
already specified in the UG
