### ISSUE TITLE
[PE-D][Tester A] 'find' command: Unable to find vendor tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-4/tp#287]
'find t/vendor' is unable to locate contacts tagged with "VENDOR".

Expected: "VENDOR" contacts shown

Actual: 
![image.png](https://raw.githubusercontent.com/QuekBingHeng/ped/main/files/9150a77a-9768-4a59-9879-ad046b1b7075.png)

Using different prefixes for the 'find' command yields the same results as shown above. Perhaps add "VENDOR" as a tag?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: QuekBingHeng/ped#4

**Comment by dasha3412** [comment]
Maybe can just add in UG that vendor is not a tag? Might just be user error though

**Comment by tingxuanp** [comment]
I feel like we can treat this as a user error cos in the UG Vendor and Tags are separate
