### ISSUE TITLE
[PE-D][Tester D] Error message bug when unassign-wedding used on big index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-4/tp#296]
Input: unassign-wedding 100 w/Tom's Wedding
![image.png](https://raw.githubusercontent.com/bigismols/ped/main/files/decbe98e-48da-46c6-8e39-a1301871be69.png)

### Issue
Error message defaults to `%d` for when index specified is out of bounds for the current person list. In the example above, 100 was used when there were only 5 in the list.

### Proposed Solution
Correct the error message to more accurately reflect the actual error made. This may guide users better when they make mistakes in their commands!

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: bigismols/ped#8

**Comment by HanB1n** [comment]
Similar to #330
