### ISSUE TITLE
[PE-D][Tester E] Edit wedding documentation inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-4/tp#312]
![Screenshot 2024-11-08 at 6.53.15 PM.png](https://raw.githubusercontent.com/kohkakohla/ped/main/files/ecda9230-446e-4618-8156-a6f5700b7f5e.png)
![Screenshot 2024-11-08 at 6.53.51 PM.png](https://raw.githubusercontent.com/kohkakohla/ped/main/files/bbdd4e67-12d3-41ac-8e0e-4a290f155cf1.png)

![Screenshot 2024-11-08 at 6.53.36 PM.png](https://raw.githubusercontent.com/kohkakohla/ped/main/files/bb70cf53-ffed-4a82-9b52-0ca14e45462f.png)
In the 3 different mentions of edit-wedding in the UG and within the app, there are 3 different implementations of how to use the command, so I was slightly confused at how to use the command.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kohkakohla/ped#7

**Comment by HanB1n** [comment]
Improve documentation.
