### ISSUE TITLE
[PE-D][Tester E] Duplicate Weddings can be made.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-4/tp#314]
![Screenshot 2024-11-08 at 5.36.49 PM.png](https://raw.githubusercontent.com/kohkakohla/ped/main/files/3852f860-60d2-4461-80ac-1558356df00f.png)

Duplicate weddings can be made by adding whitespaces between each word although each wedding is essentially the same.

Steps to recreate:
1. Run "create-wedding w/Test Wedding"
2. Run "create-wedding w/Test   Wedding"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kohkakohla/ped#8

**Comment by tingxuanp** [comment]
invalid

**Comment by HanB1n** [comment]
I think its invalid also.

**Comment by dasha3412** [comment]
Declare limitations of duplicate detection in UG commands that look for duplicates + state as planned enhancement
