### ISSUE TITLE
[PE-D][Tester E] Valid names are unable to be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-4/tp#316]
![Screenshot 2024-11-08 at 5.42.09 PM.png](https://raw.githubusercontent.com/kohkakohla/ped/main/files/457a7b37-1ebe-4f77-a72e-582001e033ba.png)

Valid names like Björn are unable to be added into the program, although I feel the expected behaviour is for those names to be able to be added.

Step to recreate:
1. Run command "add n/Björn"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kohkakohla/ped#10

**Comment by HanB1n** [comment]
This is not a bug since we mentioned alphanumeric.
