### ISSUE TITLE
[PE-D][Tester C] [BUG] Unable To Force Assign A Tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-4/tp#323]
# Issue
I am unable to force create a tag that does not exist.

![image.png](https://raw.githubusercontent.com/ahmadsyuaib/ped/main/files/b1bf6650-198c-4205-80ab-5eb5ac125eee.png)
Received message "Invalid command format!" when command is entered.

![image.png](https://raw.githubusercontent.com/ahmadsyuaib/ped/main/files/829fe2e5-107a-4707-adca-4f403a496588.png)
It is mentioned that using "f/" will force create the tag.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ahmadsyuaib/ped#10

**Comment by tingxuanp** [comment]
Will update the UG to make the instructions for the use of `f/` clearer.

**Comment by HanB1n** [comment]
I dont think this is a bug since its a user error?
